on:
  workflow_dispatch:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
name: Build Release

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository	== 'athlonreg/console'
    steps:
      - uses: actions/checkout@v2

      - name: Login to DOCKER
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate output dir
        run: |
          make container-cross

      - name: Build and push ks-console images
        uses: docker/build-push-action@v6
        if: steps.chose_registry.outputs.env == 'prod'
        with:
          context: ${{ github.workspace }}
          file: build/Dockerfile.dapper
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            docker.io/canvas1996/ks-console:v4.1.3
